# FRONTIER Configuration File
# Frustum-based Refined Object Networking & Tracking via Intersection Engine for Ranging-data

frontier:
  # Input topics
  lidar_detections_topic: "/cone/lidar/box"  # vision_msgs/Detection3DArray
  cameras:
    - id: "camera_1"
      detections_topic: "/camera_1/detections"  # vision_msgs/Detection2DArray
      camera_info_topic: "/camera_1/camera_info"     # sensor_msgs/CameraInfo
    - id: "camera_2"
      detections_topic: "/camera_2/detections"
      camera_info_topic: "/camera_2/camera_info"
  
  # Output topics
  fused_detections_topic: "/cone/fused/box"  # vision_msgs/Detection3DArray
  visualization_topic: "/frontier/visualization"         # visualization_msgs/MarkerArray
  
  # Frustum parameters
  frustum:
    near_distance: 1.0    # meters
    far_distance: 15.0    # meters

  # Adaptive frustum (monocular depth rule-based)
  adaptive_frustum:
    enabled: true
    mode: "fine"            # switched to fine for near-range boost
    object_height_m: 0.70   # 70 cm
    object_width_m: 0.30    # 30 cm
    near_min_m: 0.5
    far_max_m: 100.0        # extend far limit further
    # Fine-mode params
    margin_min: 1.40        # near (large bbox): increase margin more
    margin_max: 1.50        # far (tiny bbox): slightly lower than before
    area_thresholds: [0.10, 0.05, 0.02]
    # Coarse-mode params (ignored in fine)
    coarse_thresholds: [0.06, 0.02]
    coarse_margins: [0.50, 0.90, 1.40]
    
  # IoU calculation method
  iou:
    method: "point_in_frustum"  # Options: "point_in_frustum", "voxel", "sampling"
    n_samples: 500              # For sampling method (reduced for performance)
    voxel_size: 0.2            # For voxel method (meters) - larger for speed
    samples_per_axis: 5         # For point_in_frustum method (125 samples total)
    
  # Matching parameters
  matching:
    iou_threshold: 0.2          # Lowered to reduce false negatives
    max_distance: 70.0          # Slightly extend to avoid FNs
    method: "hungarian"         # Options: "hungarian", "greedy"
    timeout_ms: 20              # Timeout for matching algorithm
    
  # Distance-based thresholds
  distance_gates:
    near:
      max_distance: 10.0
      min_iou: 0.2
    medium:
      max_distance: 30.0
      min_iou: 0.25
    far:
      max_distance: 50.0
      min_iou: 0.3
      
  # Performance optimization (실시간성 중시)
  optimization:
    max_frustums: 50            # Increase to avoid dropping candidates
    max_boxes: 100              # Increase to avoid dropping boxes
    use_distance_gating: false  # Disable to avoid false negatives
    use_fov_gating: false       # Disable to avoid false negatives
    fov_margin_deg: 5.0         # FOV margin in degrees
    
  # Calibration files (relative to config folder)
  calibration:
    intrinsic_file: "multi_camera_intrinsic_calibration.yaml"
    extrinsic_file: "multi_camera_extrinsic_calibration.yaml"
    apply_distortion_correction: true  # Apply distortion correction in unprojection
    
  # Coordinate frames
  frames:
    lidar_frame: "os_sensor"     # LiDAR boxes are published in os_sensor frame
    base_frame: "base_link"
    
  # Time synchronization (실시간성 우선)
  sync:
    queue_size: 3                # Message queue size (reduced for low latency)
    slop_seconds: 0.2           # Slightly more tolerant sync to reduce FN
    
  # Visualization settings
  visualization:
    publish_markers: true
    publish_rate_hz: 20.0        # 시각화 주사율 (10/20/30 Hz 권장)
    frustum_color: [0.0, 1.0, 0.0, 0.3]      # Green, semi-transparent
    lidar_box_color: [0.0, 0.0, 1.0, 0.5]    # Blue
    matched_frustum_color: [1.0, 1.0, 0.0, 0.5]  # Yellow
    matched_box_color: [1.0, 0.5, 0.0, 0.7]      # Orange (fallback)
    match_line_color: [1.0, 1.0, 0.0, 0.8]       # Yellow
    text_scale: 0.15
    marker_lifetime_sec: 0.1     # 짧게 설정하여 빠른 업데이트
    # 클래스별 색상 (라벨 키워드 매칭)
    class_colors:
      yellow: [1.0, 1.0, 0.0, 0.7]
      blue:   [0.0, 0.5, 1.0, 0.7]
      orange: [1.0, 0.5, 0.0, 0.7]
      cone:   [1.0, 0.5, 0.0, 0.7]
    
  # Debug options
  debug:
    print_timings: false         # Print processing times
    print_matches: true          # Print matching results
    save_iou_matrix: false       # Save IoU matrix to file
    log_level: "info"           # Options: "debug", "info", "warn", "error"